export const conveniencesData = [
  { id: "PARKING", label: "주차" },
  { id: "PRINT", label: "프린트" },
  { id: "ELEVATOR", label: "엘리베이터" },
  { id: "PURIFIER", label: "정수기" },
  { id: "BLANKET", label: "담요" },
  { id: "BEVERAGE", label: "음료" },
  { id: "TABLET_PC", label: "태블릿 PC" },
  { id: "READING_DESK", label: "독서대" },
  { id: "WIFI", label: "와이파이" },
  { id: "NO_KIDS_ZONE", label: "노키즈존" },
  { id: "HDMI", label: "HDMI" },
  { id: "MONITOR", label: "모니터" },
  { id: "PEN", label: "보드마카" },
  { id: "BOARD", label: "화이트보드" },
  { id: "BEAM", label: "빔 프로젝터" },
  { id: "POWER_SOCKET", label: "콘센트" },
  { id: "POINTER", label: "레이저 포인터" },
  { id: "NOTEBOOK", label: "노트북" },
  { id: "AIR_CONDITIONER", label: "에어컨" },
  { id: "NO_FOOD", label: "음식물 반입 금지" },
  { id: "CHARGER", label: "충전기" },
];

export const convenienceDic = {
  PARKING: "주차",
  PRINT: "프린트",
  ELEVATOR: "엘리베이터",
  PURIFIER: "정수기",
  BLANKET: "담요",
  BEVERAGE: "음료",
  TABLET_PC: "태블릿 PC",
  READING_DESK: "독서대",
  WIFI: "와이파이",
  NO_KIDS_ZONE: "노키즈존",
  HDMI: "HDMI",
  MONITOR: "모니터",
  PEN: "보드마카",
  BOARD: "화이트보드",
  BEAM: "빔 프로젝터",
  POWER_SOCKET: "콘센트",
  POINTER: "레이저 포인터",
  NOTEBOOK: "노트북",
  AIR_CONDITIONER: "에어컨",
  NO_FOOD: "음식물 반입 금지",
  CHARGER: "충전기",
};
